"""updated table

Revision ID: 239ed16a5c88
Revises: e954ae34bd47
Create Date: 2026-03-11 08:52:28.025562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239ed16a5c88'
down_revision = 'e954ae34bd47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('land_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('land_submissions', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
