"""added column

Revision ID: 7c74ea12c976
Revises: f186fb2e00b0
Create Date: 2026-03-12 07:35:07.411670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c74ea12c976'
down_revision = 'f186fb2e00b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('land_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('approved_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('land_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('reviewed_at')

    # ### end Alembic commands ###
