"""added column

Revision ID: f186fb2e00b0
Revises: 239ed16a5c88
Create Date: 2026-03-12 07:33:54.985054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f186fb2e00b0'
down_revision = '239ed16a5c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('land_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('land_submissions', schema=None) as batch_op:
        batch_op.drop_column('approved_at')

    # ### end Alembic commands ###
